# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f67eaabd1e41e08488c48e92f6ba1ea455cb27b25e5caff5c0d6553fb481d6f6f483883ea711252603804123f4997d42a081ffa4f49db32013864576b583974f

test:
  secret_key_base: 16ad912d525743872726f6744f697e2deaabe74c590e7cb1e0f62a9a492e5aa4988d255261244a7ea53bb50706a601880c775df44c5855092f5c45e8e5c170ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
